#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."

echo "Installing pip and setuptools..."
python -m pip install pip==22.1.2 setuptools==62.6.0 wheel==0.37.1

echo "Installing requirements..."
python -m pip install -r requirements.txt
