#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."

python -m venv venv
source venv/bin/activate

. script/install-packaging

python -m pip install -r requirements.txt --require-hashes
echo "$VIRTUAL_ENV/bin" >> "$GITHUB_PATH"
echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> "$GITHUB_ENV"
