#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."

echo "Installing pip and setuptools..."
python -m pip install pip==22.2.2 setuptools==63.2.0 wheel==0.37.1

echo "Installing requirements..."
python -m pip install -r requirements.txt --require-hashes
