#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."

black . --check

# stop the build if there are Python syntax errors or undefined names
flake8 makesite.py test --count --select=E9,F63,F7,F82 --show-source --statistics
# exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
flake8 makesite.py test --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
