#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."

python -VV
echo "Virtual env path: $VIRTUAL_ENV"

. script/install-packaging

python -m pip install -U pip-tools
python -m piptools compile -v -o requirements.txt pyproject.toml --resolver backtracking --generate-hashes --upgrade
python -m piptools sync
